package bomberone.views.rules;

import bomberone.tools.ResourcesLoader;
import bomberone.views.ViewImpl;
import bomberone.views.ViewType;
import bomberone.views.ViewsSwitcher;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.text.Font;

public class RulesViewImpl extends ViewImpl implements RulesView {

    private static final int FONT_SIZE_20 = 20;
    private static final int FONT_SIZE_16 = 16;

    @FXML
    private Label rules;

    @FXML
    private Label textPU;

    @FXML
    private Label textPU1;

    @FXML
    private Label textPU2;

    @FXML
    private Label textPU3;

    @FXML
    private Label textPU4;

    @FXML
    private Label textPU5;

    @FXML
    private Label textCommands;

    private Font arcade20;
    private Font arcade16;

    /**
     * {@inheritDoc}
     */
    @Override
    public void init() {
        this.arcade20 = ResourcesLoader.getInstance().getFont(FONT_SIZE_20);
        this.arcade16 = ResourcesLoader.getInstance().getFont(FONT_SIZE_16);
        this.rules.setFont(arcade20);
        this.textPU.setFont(arcade20);
        this.textPU1.setFont(arcade16);
        this.textPU2.setFont(arcade16);
        this.textPU3.setFont(arcade16);
        this.textPU4.setFont(arcade16);
        this.textPU5.setFont(arcade16);
        this.rules.setText("BomberOne, arcade game where the main objective is to destroy all the boxes and kill all the enemies within the time limit.\n"
                + "Inside the boxes there will be PowerUps capable of enhancing the characteristics of the Bomber (described at the bottom).\n"
                + "The Bomber, starts off with 3 lives, he can die in two different ways: the first one, if he comes into contact with the fire generated by his bombs; the second one if he comes into contact with his enemies, they can to die only if they come into contact with fire.\n"
                + "Whenever the Bomber dies, all PowerUps (except TimerInc) will be deactivated. At the beginning of the game it will be possible to choose between two different levels, the first one called \"Normal\" is the less difficult, will generates 3 enemies, that, once dead, will no longer be present in the map, whereas the second one, called \"Hard\", the most difficult, will generetes more boxes and the enemies can respawn until until there will be boxes on the map. ");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public final void switchToHome() {
        ViewsSwitcher.getInstance().switchView(this.getStage(), ViewType.HOME, this.getController().getModel());
    }
}
